appName: Clean code rulez!

#server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
#  applicationConnectors:
#    - type: http
#      port: 5000
    #this requires the alpn-boot library on the JVM's boot classpath
    #- type: h2
    #  port: 8445
    #  keyStorePath: example.keystore
    #  keyStorePassword: example
    #  validateCerts: false
    #  validatePeers: false
#  adminConnectors:
#    - type: http
#      port: 5001
#server:
#  type: simple
#  connector:
#    type: http
#    port: 5050
#database:
#  # the name of your JDBC driver
#  driverClass: org.mysql.Driver
#
#  # the username
#  user: root
#
#  # the password
#  password:
#
#  # the JDBC URL
#  url: jdbc:mysql://localhost/db-prod
#
#  # any properties specific to your JDBC driver:
#  properties:
#    charSet: UTF-8
#    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#
#  # the maximum amount of time to wait on an empty pool before throwing an exception
#  maxWaitForConnection: 1s
#
#  # the SQL query to run when validating a connection's liveness
#  validationQuery: "/* MyApplication Health Check */ SELECT 1"
#
#  # the minimum number of connections to keep open
#  minSize: 8
#
#  # the maximum number of connections to keep open
#  maxSize: 32
#
#  # whether or not idle connections should be validated
#  checkConnectionWhileIdle: false